/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wyx_ndktestdemo_ndk_JNIUtils */

#ifndef _Included_com_example_wyx_ndktestdemo_ndk_JNIUtils
#define _Included_com_example_wyx_ndktestdemo_ndk_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wyx_ndktestdemo_ndk_JNIUtils
 * Method:    getStringFormC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_wyx_ndktestdemo_ndk_JNIUtils_getStringFormC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
